### ISSUE TITLE
Compile Time parameters not pre-filled

### ISSUE THREAD

**Issue by Typositoire** [sparkleformation/sfn-parameters#10]
```
"compile_parameters"=>{"AvailabilityZoneCount"=>9},
"apply_stack"=>["REDACTED", "REDACTED"],
"apply_mapping"=>{"vpc_member_security_group_id"=>"VpcSecurityGroup"}}
[Sfn]: Callback after_config_create parameters_stacks: complete
[Sfn]: Callback template stack_policy: starting
[Sfn]: Compile time parameters: - template: test-vpc
[Sfn]: AvailabilityZoneCount [3]:
```

As you can see above the compile_parameters hash has a value of 9 but SFN still gives me a default of 3.

**Comment by Typositoire** [comment]
here another example 

```
⇒  sfn create lshp-core-stg -f sparkleformation/templates/core/core.rb --debug
[Sfn]: Callback after_config_create parameters_stacks: starting
[Sfn]: Callback after_config_create parameters_stacks: complete
[DEBUG]: Merged compile parameters - {"lshp-core-stg__SubnetTiers"=>"public,mgmt,private", "lshp-core-stg__SubnetPublicTiers"=>"public,mgmt"}
[Sfn]: Compile time parameters: - template: lshp-core-stg
[Sfn]: AvailabilityZoneCount [3]:
[Sfn]: AvailabilityZones [autodetect]:
[Sfn]: SubnetTiers [public,protected,private]:
```

**Comment by Typositoire** [comment]
@chrisroberts Any idea ? They are clearly taken into account but not applied to the prompt.

**Comment by chrisroberts** [comment]
@Typositoire what version of `sfn` are you using?

**Comment by ls-yann-david** [comment]
Using sfn 3.0.20

**Comment by Typositoire** [comment]
Using sfn 3.0.20

**Comment by Typositoire** [comment]
Any update ?

**Comment by chrisroberts** [comment]
Yes, I have a handful of updates I'll be pushing out over the long weekend and this is one that will get fixed up.

**Comment by Typositoire** [comment]
Awesome thanks!

**Comment by jimcroft** [comment]
Hi Chris, any update on this one? Thanks.

**Comment by hybby** [comment]
Hitting this one too; would be good if there's a fix available.  :)

**Comment by jimcroft** [comment]
For the others on this thread: there's a fix in a branch of the sfn repo. The branch is https://github.com/sparkleformation/sfn/commits/fix/compile-time-matching

You should be able to use this by adding the following to your Gemfile.

`gem 'sfn', git: 'git@github.com: sparkleformation/sfn.git', branch: 'fix/compile-time-matching'`

**Comment by adammw** [comment]
Bumping into this again, in that compile time parameters set in parameter files seem to be overridden by any compile state already present on the stack's CompileState output, as well as that being where any defaults in prompts are coming from.

Is this by design, or a bug?
