### ISSUE TITLE
Feature request/Question: Differentiating different accounts

### ISSUE THREAD

**Issue by autarchprinceps** [sparkleformation/sfn-parameters#15]
Is there a way to differentiate stacks of the same name in different accounts? If not there should be.
I don't even mean to be able to handle stacks in different accounts for apply_stack or something like that (although that too could be useful), I primarily want to have different stack sfn-parameter files for the same stack names, but referring to stacks in different accounts, since they might have different parameters. Currently if I e.g. have a stack named networking, that would mean my file would also be named networking.json (since that is the format I prefer), but if I have networking stacks in different accounts they may have e.g. different cidr blocks as parameters.
I realise I could name them differently in different accounts, but that is not always applicable or convenient, and definitively just a workaround.

**Comment by tecracer-theinen** [comment]
It's been a while, but I'd concur on this one. I am deploying stacks to multiple customers/environments and try to have the same naming in all of those. So some distinction by account would be awesome.

**Comment by chrisroberts** [comment]
Hi! This can be accomplished by using a custom directory location in the configuration. Lets take the following configuration file:

```ruby
Configuration.new do
  credentials do
    provider :aws
    aws_access_key_id ENV["AWS_ACCESS_KEY_ID"]
    aws_secret_access_key ENV["AWS_SECRET_ACCESS_KEY"]
    aws_region ENV["AWS_REGION"]
  end
  sfn_parameters.directory File.join("stacks", ENV["AWS_REGION"])
end
```

By default, the directory used is `./stacks`. With the above configuration (assuming env vars are being used to provide credentials configuration) stack parameters can be isolated to their respective regions.

There are other ways you can define the path structure to get the behavior you need depending on your environment, but this should hopefully get you in the right direction. If you have other ideas, please do let me know. But this should be easy enough and is pretty straight forward.

Cheers!
